#!/bin/bash

CLIENT_DOMAIN_OR_SLUG=$1

LAMBDA_FN_VER_MOVE_HOST=4
LAMBDA_FN_VER_SITE_REDUCTION=23

AWS_ACCOUNT=236130610212
S3_ORIGIN_ACCESS_ID_CODE=E26DHB90474TMO
CERT_ARN_CODE="bbdde4b9-87ba-4c6e-a5ca-387bcc273a22"
WEB_ACL_ID="a2666db4-0cfe-4a45-b468-77bad12821c2"

ENV=qa
S3_ORIGIN_ACCESS_ID="origin-access-identity\/cloudfront\/${S3_ORIGIN_ACCESS_ID_CODE}"
LAMBDA_FN_ARN_MOVE_HOST="arn:aws:lambda:us-east-1:${AWS_ACCOUNT}:function:move-host-header:${LAMBDA_FN_VER_MOVE_HOST}"
LAMBDA_FN_ARN_SITE_REDUCTION="arn:aws:lambda:us-east-1:${AWS_ACCOUNT}:function:site-reduction-redirect:${LAMBDA_FN_VER_SITE_REDUCTION}"
CERT_ARN="arn:aws:acm:us-east-1:${AWS_ACCOUNT}:certificate\/${CERT_ARN_CODE}"


./generate_cf_cfg.sh  0  $CLIENT_DOMAIN_OR_SLUG  $ENV  $S3_ORIGIN_ACCESS_ID  $LAMBDA_FN_ARN_MOVE_HOST  $LAMBDA_FN_ARN_SITE_REDUCTION  $CERT_ARN  $WEB_ACL_ID


