#!/bin/bash

CLIENT_DOMAIN_OR_SLUG=$1

LAMBDA_FN_VER_MOVE_HOST=5
LAMBDA_FN_VER_SITE_REDUCTION=27

AWS_ACCOUNT=759286849978
S3_ORIGIN_ACCESS_ID_CODE=E14ZAB040LTWOF
CERT_ARN_CODE="eab18be5-057c-4358-89e3-ca3730f480b8"
WEB_ACL_ID="5b971a74-4738-4865-8a2b-746dc7505ebe"

ENV=staging
S3_ORIGIN_ACCESS_ID="origin-access-identity\/cloudfront\/${S3_ORIGIN_ACCESS_ID_CODE}"
LAMBDA_FN_ARN_MOVE_HOST="arn:aws:lambda:us-east-1:${AWS_ACCOUNT}:function:move-host-header:${LAMBDA_FN_VER_MOVE_HOST}"
LAMBDA_FN_ARN_SITE_REDUCTION="arn:aws:lambda:us-east-1:${AWS_ACCOUNT}:function:site-reduction-redirect:${LAMBDA_FN_VER_SITE_REDUCTION}"
CERT_ARN="arn:aws:acm:us-east-1:${AWS_ACCOUNT}:certificate\/${CERT_ARN_CODE}"


./generate_cf_cfg.sh  0  $CLIENT_DOMAIN_OR_SLUG  $ENV  $S3_ORIGIN_ACCESS_ID  $LAMBDA_FN_ARN_MOVE_HOST  $LAMBDA_FN_ARN_SITE_REDUCTION  $CERT_ARN  $WEB_ACL_ID


